name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*
    paths:
      - app/**
      - .github/workflow/**
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - ready_for_review
env:
  APPLICATION_NAME: flask-application
  DOCKER_USERNAME: asif21gm

jobs:

  flask-build-test-job:

    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'push' && startsWith(github.ref_name, 'feature/')) ||
      (github.event_name == 'pull_request' && github.base_ref == 'main' && !contains(github.event.pull_request.title, 'WIP'))
    steps:
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v4
    #   with:
    #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
    #     password: ${{ secrets.TOKEN }}

    - uses: actions/checkout@v4
    - name: Generate Dynamic docker image tag
      run: echo "IMAGE_TAG=v${{ github.run_number }}" >> $GITHUB_ENV    # - name: Build the Docker image
    #   run: docker build --tag cloud-with-asif:v1 .
    # - name: Build and push
    #   uses: docker/build-push-action@v7
    #   with:
    #     context: .
    #     push: true
    #     tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cloud-with-asif:v1
  
