name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*
    paths:
      - app/**
      - .github/workflow/**
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - ready_for_review
env:
  APPLICATION_NAME: flask-application
  DOCKER_USERNAME: asif21gm

jobs:

  flask-build-test-job:

    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'push' && startsWith(github.ref_name, 'feature/')) ||
      (github.event_name == 'pull_request' && github.base_ref == 'main' && !contains(github.event.pull_request.title, 'WIP'))
    steps:
    - uses: actions/checkout@v4
    - name: Generate Dynamic docker image tag
      run: echo "IMAGE_TAG=v${ GITHUB_RUN_NUMBER }-${GITHUB_SHA::7}" >> $GITHUB_ENV    # - name: Build the Docker image
    - name: Display Build Information
      run: |
        echo "Application: $APPLICATION_NAME"
        echo "Repository: $GITHUB_REPOSITORY"
        echo "Actor: $GITHUB_ACTOR"
        echo "Branch: $GITHUB_REF_NAME"
        echo "Image Tag: $IMAGE_TAG"
  
    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v7
      with:
        context: ./app
        push: false
        tags: ${{ env.DOCKER_USERNAME }}/${{ env.APPLICATION_NAME }}:${ env.IMAGE_TAG }
    - name: Run Container
      run: |
        docker run -d \
          -p 5000:5000 \
          --name flask-container \
          $DOCKER_USERNAME/$APPLICATION_NAME:$IMAGE_TAG

    - name: Smoke Test Application
      run: |
        sleep 5
        curl --fail http://localhost:5000
        curl --fail http://localhost:5000/health
    - name: push if the previous step are succesfull
      if: ${{ success() }}
      run: |
          docker push $DOCKER_USERNAME/$APPLICATION_NAME:$IMAGE_TAG
    - name: if fails
      if: ${{ failure() }}
      run: docker logs flask-container
    - name: Cleanup
      run: dokcer rm -f flask-container || true