name: my first workflow
on: 
  #push:
  workflow_dispatch:
  #schedule:
   # - cron: "*/5 * * * *"

jobs:
  job-1:
    runs-on: ubuntu-24.04
    steps:
      - name: step1
        run: echo "Hello this is first step"
      - name: step2
        run: echo "this is second step"
  job-2:
    runs-on: ubuntu-24.04
    needs: job-1
    steps:
      - name: step1 of job2
        run: echo "Hello this is first step of job-2"
 
