name: github outs
on:
  workflow_dispatch:


jobs:
    deployment-job:
        runs-on: ubuntu-latest
        steps:
        - name: deploy application
          id: deploy
          run: |
              echo "Deploying application..."
              sleep 5
              echo "deployment_url=https://localhost:8080" >> $GITHUB_OUTPUT
        - name: dispaly the deployment url
          run: |
              echo "Deployment URL: ${{ steps.deploy.outputs.deployment_url }}"
        - name: send deployment url notification
          run: |
            echo "sending deployment url notification..."
            echo "Deployment URL: ${{ steps.deploy.outputs.deployment_url }}"
            echo "deployment notification sent successfully!"
        outputs:
            deployment_url: ${{ steps.deploy.outputs.deployment_url }}
    notification-job:
        needs: deployment-job
        runs-on: ubuntu-latest
        steps:
           - name: outputing job output notification
             run: |
                echo "sending deployment notification ..."
                echo "job output deployement url: ${{ needs.deployment-job.outputs.deployment_url }}"
